# My Jupiter Notebook on IBM Watson Studio

**André Gustavo Di Palma Cordovil**  
Petroleum Engineer

*I work with tons of different types of data regurlary and I need to learn how to deal and use it generating useful and significant insights*

### My code will calculated a inverse of a mattrix

In [8]:
#### import numpy as np
###Defining the original matrix
A = np.array([[1, 4, 3],[4, 5, 6],[7, 1, 9]])
A

array([[1, 4, 3],
       [4, 5, 6],
       [7, 1, 9]])

In [9]:
###Obtaining the inverse
A_Inv=np.linalg.inv(A)
A_Inv

array([[-1.3       ,  1.1       , -0.3       ],
       [-0.2       ,  0.4       , -0.2       ],
       [ 1.03333333, -0.9       ,  0.36666667]])

In [13]:
###Confirming the identity as the result of the multiplication of the original mattrix per its inverse
Mult=A@A_Inv
Mult


array([[ 1.00000000e+00, -3.33066907e-16,  1.11022302e-16],
       [ 4.44089210e-16,  1.00000000e+00,  2.22044605e-16],
       [ 6.66133815e-16, -9.99200722e-16,  1.00000000e+00]])

In [12]:
Ident=np.eye(3,3)
Ident

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## The end